# Generated by Django 3.2.4 on 2021-06-16 10:43

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=catalog.models.Language, to='catalog.language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(help_text='Enter a language for the book (e.g. English)', max_length=100),
        ),
    ]
