# Generated by Django 3.2.4 on 2021-06-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_auto_20210629_1641"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="date_of_death",
            field=models.DateField(blank=True, null=True, verbose_name="died"),
        ),
    ]
